version: 2

models:
  - name: sources
    description: Modelo base sobre fontes de dados. Uma linha por execução de nó.
    columns:
      - name: command_invocation_id
        description: '{{ doc("command_invocation_id") }}'
      - name: node_id
        description: '{{ doc("node_id") }}'
      - name: run_started_at
        description: '{{ doc("run_started_at") }}'
      - name: database
        description: '{{ doc("database") }}'
      - name: schema
        description: '{{ doc("schema") }}'
      - name: source_name
        description: '{{ doc("source_name") }}'
      - name: loader
        description: '{{ doc("loader") }}'
      - name: name
        description: '{{ doc("name") }}'
      - name: identifier
        description: '{{ doc("identifier") }}'
      - name: loaded_at_field
        description: '{{ doc("loaded_at_field") }}'
      - name: freshness
        description: '{{ doc("freshness") }}'
      - name: all_results
        description: '{{ doc("all_results") }}'
    config:
      group: Cloud Data Analytics